Add tutorial
Aayush-Ankit/dpe_emulate pull request #4
Opened 2019-06-25 18:37 UTC by Izabellaaaq

2019-06-25 20:03 UTC, glaucimar requested changes
Thanks Izabella, very good documentation. Please, observe my comments before merging.

2019-06-25 20:03 UTC, glaucimar commented on how_to_run.md
> +git clone https://izabellaaaq@bitbucket.org/izzat/dpe.git
First, you should not use your user here. and second, let's use the public puma compile repo: https://github.com/illinois-impact/puma-compiler

So, the line should be: git clone https://github.com/illinois-impact/puma-compiler

2019-06-25 20:03 UTC, glaucimar commented on how_to_run.md
> +cd /puma-simulator/src
cd "PATH TO PUMA SIMULATOR"/src    ?

2019-06-25 20:03 UTC, glaucimar commented on how_to_run.md
> +### 1. Create DPE folder and go to the folder:
Create DPE folder and change to the folder:

2019-06-27 16:56 UTC, Aayush-Ankit requested changes
Thanks Izabella. This tutorial is great!
Can we update "dpe" to "puma" in Lines 11, 13 and 14 ?

2019-06-27 17:01 UTC, glaucimar approved these changes
Thanks for addressing comments, Izabella!

2019-06-28 00:52 UTC, Aayush-Ankit approved these changes

2019-06-28 00:53 UTC, merged